### ISSUE TITLE
Can't block all of the ads

### ISSUE THREAD

**Issue by gh-legacy** [MoonchildProductions/adblock-latitude#32]
This extension can't block all of the ads on this site: [https://genk.vn](url)

Only Ublock Origin Legacy could handle it.

I report because I think it's the problem with the extension itself, not EasyList. Since IE11 with EasyList on Windows 7 could handle all of the ads on this site just well.

p/s: I manually enabled EasyList alongside with the default filter.

**Comment by wolfbeast** [comment]
Easylist uses entries in a format not fully supported by ABL, which is why.
You can always add custom filters to your list to filter additional ads on the sites you visit.
