### ISSUE TITLE
saving webpages with ad filtering effects included

### ISSUE THREAD

**Issue by keenla** [MoonchildProductions/adblock-latitude#34]
Is there a setting in About:config or somewhere else(what to search??), that allows saving WYSIWYG webpage in a form of *.mht or *.maff file with all ABL- and eMatrix- style filtering effects included?
And if there is, maybe add a quick-linking checkbox into ABL options page?

**Comment by wolfbeast** [comment]
Please ask on the [Pale Moon forum](https://forum.palemoon.org).
